#include "inc/func_records.h"

// Full list of supported function records
T_FuncRec g_FuncRecs[] =
{
	// debugapi.h
	{"CheckRemoteDebuggerPresent", 0, 0},
	{"ContinueDebugEvent", 0, 0},
	{"DebugActiveProcess", 0, 0},
	{"DebugActiveProcessStop", 0, 0},
	{"DebugBreak", 0, 0},
	{"IsDebuggerPresent", 0, 0},
	{"OutputDebugStringA", 0, 0},
	{"OutputDebugStringW", 0, 0},
	{"WaitForDebugEvent", 0, 0},
	// fileapi.h
	{"CreateDirectoryA", 0, 0},
	{"CreateDirectoryW", 0, 0},
	{"CreateFileA", 0, 0},
	{"CreateFileW", 0, 0},
	{"DeleteFileA", 0, 0},
	{"DeleteFileW", 0, 0},
	{"GetFileSize", 0, 0},
	{"GetFileSizeEx", 0, 0},
	{"GetFileType", 0, 0},
	{"ReadFile", 0, 0},
	{"ReadFileEx", 0, 0},
	{"RemoveDirectoryA", 0, 0},
	{"RemoveDirectoryW", 0, 0},
	{"SetEndOfFile", 0, 0},
	{"SetFilePointer", 0, 0},
	{"SetFilePointerEx", 0, 0},
	{"WriteFile", 0, 0},
	{"WriteFileEx", 0, 0},
	// heapapi.h
	{"GetProcessHeap", 0, 0},
	{"GetProcessHeaps", 0, 0},
	{"HeapAlloc", 0, 0},
	{"HeapCompact", 0, 0},
	{"HeapCreate", 0, 0},
	{"HeapDestroy", 0, 0},
	{"HeapFree", 0, 0},
	{"HeapLock", 0, 0},
	{"HeapQueryInformation", 0, 0},
	{"HeapReAlloc", 0, 0},
	{"HeapSetInformation", 0, 0},
	{"HeapSize", 0, 0},
	{"HeapUnlock", 0, 0},
	{"HeapValidate", 0, 0},
	{"HeapWalk", 0, 0},
	// memoryapi.h
	{"CreateFileMappingA", 0, 0},
	{"CreateFileMappingW", 0, 0},
	{"FlushViewOfFile", 0, 0},
	{"MapViewOfFile", 0, 0},
	{"MapViewOfFileEx", 0, 0},
	{"OpenFileMappingA", 0, 0},
	{"OpenFileMappingW", 0, 0},
	{"UnmapViewOfFile", 0, 0},
	{"VirtualAlloc", 0, 0},
	{"VirtualAllocEx", 0, 0},
	{"VirtualFree", 0, 0},
	{"VirtualFreeEx", 0, 0},
	{"VirtualLock", 0, 0},
	{"VirtualProtect", 0, 0},
	{"VirtualProtectEx", 0, 0},
	{"VirtualQuery", 0, 0},
	{"VirtualQueryEx", 0, 0},
	{"VirtualUnlock", 0, 0},
	// processthreadsapi.h
	{"CreateProcessA", 0, 0},
	{"CreateProcessW", 0, 0},
	{"CreateProcessAsUserA", 0, 0},
	{"CreateProcessAsUserW", 0, 0},
	{"CreateRemoteThread", 0, 0},
	{"CreateRemoteThreadEx", 0, 0},
	{"CreateThread", 0, 0},
	{"DeleteProcThreadAttributeList", 0, 0},
	{"ExitProcess", 0, 0},
	{"ExitThread", 0, 0},
	{"GetCurrentProcess", 0, 0},
	{"GetCurrentProcessId", 0, 0},
	{"ResumeThread", 0, 0},
	{"SuspendThread", 0, 0},
	{"TerminateProcess", 0, 0},
	{"TerminateThread", 0, 0},
	// profileapi.h
	{"QueryPerformanceCounter", 0, 0},
	{"QueryPerformanceFrequency", 0, 0},
	// winuser.h
	{"AdjustWindowRect", 0, 0},
	{"AdjustWindowRectEx", 0, 0},
	{"BeginPaint", 0, 0},
	{"ClientToScreen", 0, 0},
	{"ClipCursor", 0, 0},
	{"CloseWindow", 0, 0},
	{"CreateWindowA", 0, 0},
	{"CreateWindowW", 0, 0},
	{"CreateWindowExA", 0, 0},
	{"CreateWindowExW", 0, 0},
	{"DefWindowProc", 0, 0},
	{"DestroyWindow", 0, 0},
	{"DispatchMessageA", 0, 0},
	{"DispatchMessageW", 0, 0},
	{"EndPaint", 0, 0},
	{"FillRect", 0, 0},
	{"GetClientRect", 0, 0},
	{"GetCursorPos", 0, 0},
	{"GetDC", 0, 0},
	{"GetMessageA", 0, 0},
	{"GetMessageW", 0, 0},
	{"GetWindowRect", 0, 0},
	{"MessageBoxA", 0, 0},
	{"MessageBoxW", 0, 0},
	{"MessageBoxExA", 0, 0},
	{"MessageBoxExW", 0, 0},
	{"PeekMessageA", 0, 0},
	{"PeekMessageW", 0, 0},
	{"PostMessageA", 0, 0},
	{"PostMessageW", 0, 0},
	{"PostQuitMessage", 0, 0},
	{"RegisterClassExA", 0, 0},
	{"RegisterClassExW", 0, 0},
	{"ReleaseDC", 0, 0},
	{"ScreenToClient", 0, 0},
	{"ShowCursor", 0, 0},
	{"ShowWindow", 0, 0},
	{"TranslateMessage", 0, 0},
	{"UpdateWindow", 0, 0}
};

